version: "3.9"

services:

  warden-db-mariadb:
    image: mariadb:10.11
    hostname: warden-db-mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: warden
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - warden-db-mariadb-data:/var/lib/mysql

  warden-db-postgres:
    image: postgres:16
    hostname: warden-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: warden
      POSTGRES_USER: wardenuser
      POSTGRES_PASSWORD: secret
    volumes:
      - warden-db-postgres-data:/var/lib/postgresql/data

volumes:
  warden-db-mariadb-data:
  warden-db-postgres-data:
