"""add scheduled_at and canceled_at datetimes

Revision ID: 6c4fad0bfc30
Revises: 9daa68354a57
Create Date: 2026-06-11 15:42:57.133242

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c4fad0bfc30"
down_revision: Union[str, Sequence[str], None] = "9daa68354a57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "canceled_at")
    op.drop_column("jobs", "scheduled_at")
    # ### end Alembic commands ###
