"""Add job logs

Revision ID: bdfad8e5b387
Revises: da94eef65e12
Create Date: 2026-04-21 08:40:35.453263

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdfad8e5b387"
down_revision: Union[str, Sequence[str], None] = "da94eef65e12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "logs",
            sa.Text().with_variant(sa.Text(length=16777215), "mysql"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "logs")
    # ### end Alembic commands ###
